# Generated by Django 5.0.6 on 2026-03-24 20:23

import apps.ordenes.models
import core.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('imagen', models.ImageField(upload_to=apps.ordenes.models.evidencia_upload_path, verbose_name='Imagen')),
                ('tipo', models.CharField(choices=[('recepcion', 'Recepción'), ('proceso', 'En proceso'), ('entrega', 'Entrega')], max_length=20, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Evidencia',
                'verbose_name_plural': 'Evidencias',
                'db_table': 'evidencias',
                'ordering': ['-created_at'],
            },
            bases=(core.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('numero_orden', models.CharField(blank=True, max_length=25, unique=True, verbose_name='Número de orden')),
                ('problema_reportado', models.TextField(verbose_name='Problema reportado')),
                ('diagnostico', models.TextField(blank=True, verbose_name='Diagnóstico')),
                ('estado', models.CharField(choices=[('recibido', 'Recibido'), ('diagnostico', 'En diagnóstico'), ('esperando_refaccion', 'Esperando refacción'), ('en_reparacion', 'En reparación'), ('listo', 'Listo para entregar'), ('entregado', 'Entregado')], default='recibido', max_length=25, verbose_name='Estado')),
                ('costo_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo estimado')),
                ('costo_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo final')),
            ],
            options={
                'verbose_name': 'Orden de servicio',
                'verbose_name_plural': 'Órdenes de servicio',
                'db_table': 'ordenes',
                'ordering': ['-created_at'],
            },
            bases=(core.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OrdenRefaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
            ],
            options={
                'verbose_name': 'Refacción en orden',
                'verbose_name_plural': 'Refacciones en orden',
                'db_table': 'ordenes_refacciones',
            },
            bases=(core.mixins.AuditableMixin, models.Model),
        ),
    ]
