# Generated by Django 5.0.6 on 2026-03-24 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_initial'),
        ('inventario', '0001_initial'),
        ('ordenes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencia',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_subidas', to=settings.AUTH_USER_MODEL, verbose_name='Subido por'),
        ),
        migrations.AddField(
            model_name='orden',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Técnico asignado'),
        ),
        migrations.AddField(
            model_name='orden',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='orden',
            name='delivered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_entregadas', to=settings.AUTH_USER_MODEL, verbose_name='Entregado por'),
        ),
        migrations.AddField(
            model_name='orden',
            name='dispositivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='clientes.dispositivo', verbose_name='Dispositivo'),
        ),
        migrations.AddField(
            model_name='orden',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Recibido físicamente por'),
        ),
        migrations.AddField(
            model_name='orden',
            name='status_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_estado_actualizado', to=settings.AUTH_USER_MODEL, verbose_name='Último cambio de estado por'),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='ordenes.orden', verbose_name='Orden'),
        ),
        migrations.AddField(
            model_name='ordenrefaccion',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refacciones_agregadas', to=settings.AUTH_USER_MODEL, verbose_name='Agregado por'),
        ),
        migrations.AddField(
            model_name='ordenrefaccion',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refacciones_usadas', to='ordenes.orden', verbose_name='Orden'),
        ),
        migrations.AddField(
            model_name='ordenrefaccion',
            name='refaccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos_en_ordenes', to='inventario.refaccion', verbose_name='Refacción'),
        ),
    ]
