# Generated by Django 5.0.6 on 2026-04-21 21:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_idx_clientes_nombre_and_more'),
        ('ordenes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='evidencia',
            index=models.Index(fields=['tipo'], name='idx_evidencias_tipo'),
        ),
        migrations.AddIndex(
            model_name='orden',
            index=models.Index(fields=['estado'], name='idx_ordenes_estado'),
        ),
        migrations.AddIndex(
            model_name='orden',
            index=models.Index(fields=['created_at'], name='idx_ordenes_created_at'),
        ),
        migrations.AddIndex(
            model_name='orden',
            index=models.Index(fields=['estado', 'created_at'], name='idx_ordenes_estado_fecha'),
        ),
    ]
