# Generated by Django 5.0.6 on 2026-05-15 20:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_idx_clientes_nombre_and_more'),
        ('ordenes', '0003_evidencia_idx_evidencias_tipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='orden',
            index=models.Index(fields=['estado', 'assigned_to'], name='idx_ordenes_estado_assigned'),
        ),
    ]
