# Generated by Django 5.0.6 on 2026-05-12 03:16

import core.mixins
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0003_cliente_idx_clientes_nombre_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaDispositivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                (
                    "nombre",
                    models.CharField(max_length=80, unique=True, verbose_name="Nombre"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=80, unique=True, verbose_name="Slug"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "orden",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Orden de visualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría de dispositivo",
                "verbose_name_plural": "Categorías de dispositivo",
                "db_table": "cotizacion_categorias",
                "ordering": ["orden", "nombre"],
            },
            bases=(core.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Cotizacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                (
                    "numero_cotizacion",
                    models.CharField(
                        blank=True,
                        max_length=25,
                        unique=True,
                        verbose_name="Número de cotización",
                    ),
                ),
                (
                    "nombre_cliente",
                    models.CharField(
                        help_text="Nombre tal como aparecerá en la cotización (cliente nuevo o existente).",
                        max_length=150,
                        verbose_name="Nombre del cliente",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("finalizada", "Finalizada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="borrador",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                ("notas", models.TextField(blank=True, verbose_name="Notas")),
            ],
            options={
                "verbose_name": "Cotización",
                "verbose_name_plural": "Cotizaciones",
                "db_table": "cotizaciones",
                "ordering": ["-created_at"],
            },
            bases=(core.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name="CotizacionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                (
                    "fuente",
                    models.CharField(
                        choices=[
                            ("api1", "API FixOEM"),
                            ("api2", "API SupraTec"),
                            ("manual", "Manual"),
                        ],
                        max_length=20,
                        verbose_name="Fuente",
                    ),
                ),
                (
                    "producto_titulo",
                    models.CharField(
                        help_text="Título del producto en la API o descripción manual.",
                        max_length=300,
                        verbose_name="Producto",
                    ),
                ),
                (
                    "precio_base",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Precio sin fórmula aplicada (de la API o ingresado manualmente).",
                        max_digits=10,
                        verbose_name="Precio base",
                    ),
                ),
                (
                    "precio_final",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Precio con la fórmula aplicada (o ingresado manualmente si es personalizado).",
                        max_digits=10,
                        verbose_name="Precio final",
                    ),
                ),
                (
                    "formula_snapshot",
                    models.CharField(
                        blank=True,
                        help_text="Texto de la fórmula al momento de generar el item. Ej: precio*2+400",
                        max_length=80,
                        verbose_name="Fórmula aplicada (snapshot)",
                    ),
                ),
                (
                    "es_personalizado",
                    models.BooleanField(
                        default=False,
                        help_text="True si el precio se ingresó manualmente (sin fórmula).",
                        verbose_name="Fue personalizado",
                    ),
                ),
                (
                    "link_referencia",
                    models.URLField(
                        blank=True,
                        help_text="URL opcional (de dónde se obtiene la pieza). Solo visible en PDF empresa.",
                        max_length=500,
                        verbose_name="Link de referencia",
                    ),
                ),
                (
                    "disponible",
                    models.BooleanField(
                        default=True,
                        help_text='Disponibilidad del producto (de la API "available") al momento de cotizar.',
                        verbose_name="Disponible",
                    ),
                ),
                (
                    "cantidad",
                    models.PositiveIntegerField(default=1, verbose_name="Cantidad"),
                ),
            ],
            options={
                "verbose_name": "Item de cotización",
                "verbose_name_plural": "Items de cotización",
                "db_table": "cotizacion_items",
                "ordering": ["created_at"],
            },
            bases=(core.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name="FormulaReparacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                (
                    "es_personalizado",
                    models.BooleanField(
                        default=False,
                        help_text="Si está activo, no se aplica fórmula y el precio se ingresa manualmente.",
                        verbose_name="Es personalizado",
                    ),
                ),
                (
                    "multiplicador",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Ejemplo: 2.00 para multiplicar por 2.",
                        max_digits=6,
                        null=True,
                        verbose_name="Multiplicador",
                    ),
                ),
                (
                    "incremento",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cantidad a sumar al resultado. Ejemplo: 400.00",
                        max_digits=10,
                        null=True,
                        verbose_name="Incremento",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Fórmula de reparación",
                "verbose_name_plural": "Fórmulas de reparación",
                "db_table": "cotizacion_formulas",
                "ordering": ["tipo_reparacion", "subcategoria"],
            },
            bases=(core.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name="SubcategoriaDispositivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                ("nombre", models.CharField(max_length=80, verbose_name="Nombre")),
                ("slug", models.SlugField(max_length=80, verbose_name="Slug")),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "orden",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Orden de visualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Subcategoría de dispositivo",
                "verbose_name_plural": "Subcategorías de dispositivo",
                "db_table": "cotizacion_subcategorias",
                "ordering": ["categoria", "orden", "nombre"],
            },
            bases=(core.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name="TipoReparacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                ("nombre", models.CharField(max_length=120, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "orden",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Orden de visualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de reparación",
                "verbose_name_plural": "Tipos de reparación",
                "db_table": "cotizacion_tipos_reparacion",
                "ordering": ["categoria", "orden", "nombre"],
            },
            bases=(core.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ApiProductoCatalogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                (
                    "fuente",
                    models.CharField(
                        choices=[("fixoem", "FixOEM"), ("supratecmx", "SupraTecMX")],
                        max_length=20,
                        verbose_name="Fuente",
                    ),
                ),
                (
                    "producto_id_externo",
                    models.BigIntegerField(verbose_name="ID externo"),
                ),
                ("titulo", models.CharField(max_length=500, verbose_name="Título")),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio"
                    ),
                ),
                (
                    "disponible",
                    models.BooleanField(default=False, verbose_name="Disponible"),
                ),
                (
                    "handle",
                    models.CharField(blank=True, max_length=300, verbose_name="Handle"),
                ),
                (
                    "vendor",
                    models.CharField(blank=True, max_length=200, verbose_name="Vendor"),
                ),
                (
                    "product_type",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Tipo de producto"
                    ),
                ),
                (
                    "synced_at",
                    models.DateTimeField(auto_now=True, verbose_name="Sincronizado en"),
                ),
            ],
            options={
                "verbose_name": "Producto API (catálogo)",
                "verbose_name_plural": "Productos API (catálogo)",
                "db_table": "api_productos_catalogo",
                "ordering": ["titulo"],
                "indexes": [
                    models.Index(fields=["fuente"], name="idx_apiproducto_fuente"),
                    models.Index(
                        fields=["disponible"], name="idx_apiproducto_disponible"
                    ),
                    models.Index(fields=["titulo"], name="idx_apiproducto_titulo"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="apiproductocatalogo",
            constraint=models.UniqueConstraint(
                fields=("fuente", "producto_id_externo"),
                name="uq_apiproducto_fuente_externo",
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                help_text="Cliente existente del sistema. Opcional si es cliente nuevo.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cotizaciones",
                to="clientes.cliente",
                verbose_name="Cliente registrado",
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cotizaciones_creadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Generada por",
            ),
        ),
        migrations.AddField(
            model_name="cotizacionitem",
            name="added_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cotizacion_items_agregados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Agregado por",
            ),
        ),
        migrations.AddField(
            model_name="cotizacionitem",
            name="cotizacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="cotizaciones.cotizacion",
                verbose_name="Cotización",
            ),
        ),
        migrations.AddField(
            model_name="subcategoriadispositivo",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategorias",
                to="cotizaciones.categoriadispositivo",
                verbose_name="Categoría",
            ),
        ),
        migrations.AddField(
            model_name="formulareparacion",
            name="subcategoria",
            field=models.ForeignKey(
                blank=True,
                help_text="Dejar vacío para aplicar a cualquier subcategoría.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="formulas",
                to="cotizaciones.subcategoriadispositivo",
                verbose_name="Subcategoría",
            ),
        ),
        migrations.AddField(
            model_name="cotizacionitem",
            name="subcategoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items_cotizacion",
                to="cotizaciones.subcategoriadispositivo",
                verbose_name="Subcategoría",
            ),
        ),
        migrations.AddField(
            model_name="tiporeparacion",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tipos_reparacion",
                to="cotizaciones.categoriadispositivo",
                verbose_name="Categoría",
            ),
        ),
        migrations.AddField(
            model_name="formulareparacion",
            name="tipo_reparacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="formulas",
                to="cotizaciones.tiporeparacion",
                verbose_name="Tipo de reparación",
            ),
        ),
        migrations.AddField(
            model_name="cotizacionitem",
            name="tipo_reparacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items_cotizacion",
                to="cotizaciones.tiporeparacion",
                verbose_name="Tipo de reparación",
            ),
        ),
        migrations.AddIndex(
            model_name="cotizacion",
            index=models.Index(fields=["estado"], name="idx_cotizaciones_estado"),
        ),
        migrations.AddIndex(
            model_name="cotizacion",
            index=models.Index(fields=["created_at"], name="idx_cotizaciones_created"),
        ),
        migrations.AddIndex(
            model_name="cotizacion",
            index=models.Index(
                fields=["numero_cotizacion"], name="idx_cotizaciones_numero"
            ),
        ),
        migrations.AddConstraint(
            model_name="subcategoriadispositivo",
            constraint=models.UniqueConstraint(
                fields=("categoria", "slug"), name="uq_subcategoria_categoria_slug"
            ),
        ),
        migrations.AddIndex(
            model_name="tiporeparacion",
            index=models.Index(fields=["activo"], name="idx_tiporep_activo"),
        ),
        migrations.AddConstraint(
            model_name="tiporeparacion",
            constraint=models.UniqueConstraint(
                fields=("categoria", "nombre"),
                name="uq_tiporeparacion_categoria_nombre",
            ),
        ),
        migrations.AddConstraint(
            model_name="formulareparacion",
            constraint=models.UniqueConstraint(
                fields=("tipo_reparacion", "subcategoria"),
                name="uq_formula_tipo_subcategoria",
            ),
        ),
    ]
