# Generated by Django 5.0.6 on 2026-05-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0007_athome_fuente_data'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='apiproductocatalogo',
            index=models.Index(fields=['fuente', 'disponible'], name='idx_apiproducto_fuente_disp'),
        ),
    ]
