# Generated by Django 5.0.6 on 2026-05-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cotizaciones", "0008_add_performance_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fuenteapi",
            name="base_url",
            field=models.CharField(
                help_text="URL raíz (Shopify), ruta al directorio de archivos JSON (athome_v1) o URL del catálogo HTML (athome_web). Ej: https://fixoem.com, data/athome, https://www.athomemx.mx/productos",
                max_length=500,
                verbose_name="URL / ruta base",
            ),
        ),
        migrations.AlterField(
            model_name="fuenteapi",
            name="tipo_parser",
            field=models.CharField(
                choices=[
                    ("shopify_v1", "Shopify v1 (products.json paginado)"),
                    ("athome_v1", "AtHome v1 (archivos JSON locales)"),
                    ("athome_web", "AtHome web (scraping JSON-LD en vivo)"),
                ],
                default="shopify_v1",
                help_text="Estrategia para descargar/parsear productos.",
                max_length=20,
                verbose_name="Tipo de parser",
            ),
        ),
    ]
