# Generated by Django 5.0.6 on 2026-04-21 21:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['nombre'], name='idx_clientes_nombre'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['telefono'], name='idx_clientes_telefono'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['email'], name='idx_clientes_email'),
        ),
        migrations.AddIndex(
            model_name='dispositivo',
            index=models.Index(fields=['tipo'], name='idx_dispositivos_tipo'),
        ),
        migrations.AddIndex(
            model_name='dispositivo',
            index=models.Index(fields=['marca'], name='idx_dispositivos_marca'),
        ),
    ]
