# Generated by Django 5.0.6 on 2026-03-24 20:23

import core.mixins
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Refaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('categoria', models.CharField(blank=True, max_length=100, verbose_name='Categoría')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock actual')),
                ('stock_minimo', models.PositiveIntegerField(default=1, verbose_name='Stock mínimo')),
                ('precio_costo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio costo')),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio venta')),
            ],
            options={
                'verbose_name': 'Refacción',
                'verbose_name_plural': 'Refacciones',
                'db_table': 'refacciones',
                'ordering': ['nombre'],
            },
            bases=(core.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RefaccionCompatible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('tipo_dispositivo', models.CharField(blank=True, max_length=50, verbose_name='Tipo de dispositivo')),
                ('refaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibilidades', to='inventario.refaccion', verbose_name='Refacción')),
            ],
            options={
                'verbose_name': 'Compatibilidad de refacción',
                'verbose_name_plural': 'Compatibilidades de refacciones',
                'db_table': 'refacciones_compatibles',
            },
            bases=(core.mixins.AuditableMixin, models.Model),
        ),
    ]
