# Generated by Django 5.0.6 on 2026-04-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='refaccion',
            index=models.Index(fields=['nombre'], name='idx_refacciones_nombre'),
        ),
        migrations.AddIndex(
            model_name='refaccion',
            index=models.Index(fields=['categoria'], name='idx_refacciones_categoria'),
        ),
        migrations.AddIndex(
            model_name='refaccion',
            index=models.Index(fields=['stock'], name='idx_refacciones_stock'),
        ),
        migrations.AddIndex(
            model_name='refaccioncompatible',
            index=models.Index(fields=['marca'], name='idx_refcompat_marca'),
        ),
    ]
