# Generated by Django 5.0.6 on 2026-05-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_refaccion_idx_refacciones_nombre_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='refaccion',
            index=models.Index(fields=['stock', 'stock_minimo'], name='idx_refacciones_stock_min'),
        ),
    ]
