# Generated by Django 5.0.6 on 2026-04-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['rol'], name='idx_usuarios_rol'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['activo'], name='idx_usuarios_activo'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['rol', 'activo'], name='idx_usuarios_rol_activo'),
        ),
    ]
