# Generated by Django 5.0.6 on 2026-03-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('ASSIGN', 'Asignar'), ('STATUS_CHANGE', 'Cambio de estado'), ('LOGIN', 'Inicio de sesión')], max_length=20, verbose_name='Acción')),
                ('entity', models.CharField(max_length=100, verbose_name='Entidad')),
                ('entity_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ID de entidad')),
                ('old_value', models.JSONField(blank=True, default=dict, verbose_name='Valor anterior')),
                ('new_value', models.JSONField(blank=True, default=dict, verbose_name='Valor nuevo')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
