# Generated by Django 5.0.6 on 2026-05-15 20:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0003_auditlog_idx_auditlog_entity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'entity'], name='idx_auditlog_action_entity'),
        ),
    ]
